//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Infrastructure.Properties.DatabaseResources", typeof(DatabaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsJson.
        /// </summary>
        internal static string AttributeJson {
            get {
                return ResourceManager.GetString("AttributeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBConnection.
        /// </summary>
        internal static string ConnectionDB
        {
            get {
                return ResourceManager.GetString("ConnectionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_delete_{0}.
        /// </summary>
        internal static string ProcedureDelete {
            get {
                return ResourceManager.GetString("ProcedureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @h_{0}_id.
        /// </summary>
        internal static string ProcedureEntityId {
            get {
                return ResourceManager.GetString("ProcedureEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_get_{0}s.
        /// </summary>
        internal static string ProcedureGetAll {
            get {
                return ResourceManager.GetString("ProcedureGetAll", resourceCulture);
            }
        }
        internal static string ProcedureGetDataHome
        {
            get
            {
                return ResourceManager.GetString("ProcedureGetDataHome", resourceCulture);
            }
        }
        internal static string ProcedureGetDataHot
        {
            get
            {
                return ResourceManager.GetString("ProcedureGetDataHot", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to proc_get_{0}_by_id.
        /// </summary>
        internal static string ProcedureGetById {
            get {
                return ResourceManager.GetString("ProcedureGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_insert_{0}.
        /// </summary>
        internal static string ProcedureInsert {
            get {
                return ResourceManager.GetString("ProcedureInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_update_{0}.
        /// </summary>
        internal static string ProcedureUpdate {
            get {
                return ResourceManager.GetString("ProcedureUpdate", resourceCulture);
            }
        }
    }
}
