--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/13/2021 8:27:42 AM
-- Server version: 8.0.26
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE webnoithat;

--
-- Drop procedure `proc_delete_user`
--
DROP PROCEDURE IF EXISTS proc_delete_user;

--
-- Drop procedure `proc_get_total_user`
--
DROP PROCEDURE IF EXISTS proc_get_total_user;

--
-- Drop procedure `proc_get_users`
--
DROP PROCEDURE IF EXISTS proc_get_users;

--
-- Drop procedure `proc_get_users_filter`
--
DROP PROCEDURE IF EXISTS proc_get_users_filter;

--
-- Drop procedure `proc_get_user_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_user_by_id;

--
-- Drop procedure `proc_get_user_by_username`
--
DROP PROCEDURE IF EXISTS proc_get_user_by_username;

--
-- Drop procedure `proc_insert_user`
--
DROP PROCEDURE IF EXISTS proc_insert_user;

--
-- Drop procedure `proc_update_user`
--
DROP PROCEDURE IF EXISTS proc_update_user;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop procedure `proc_delete_news`
--
DROP PROCEDURE IF EXISTS proc_delete_news;

--
-- Drop procedure `proc_get_news_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_news_by_id;

--
-- Drop procedure `proc_get_news_event`
--
DROP PROCEDURE IF EXISTS proc_get_news_event;

--
-- Drop procedure `proc_get_news_home`
--
DROP PROCEDURE IF EXISTS proc_get_news_home;

--
-- Drop procedure `proc_get_news_hot`
--
DROP PROCEDURE IF EXISTS proc_get_news_hot;

--
-- Drop procedure `proc_get_news_product`
--
DROP PROCEDURE IF EXISTS proc_get_news_product;

--
-- Drop procedure `proc_get_news_sale`
--
DROP PROCEDURE IF EXISTS proc_get_news_sale;

--
-- Drop procedure `proc_get_newss`
--
DROP PROCEDURE IF EXISTS proc_get_newss;

--
-- Drop procedure `proc_get_newss_filter`
--
DROP PROCEDURE IF EXISTS proc_get_newss_filter;

--
-- Drop procedure `proc_get_total_news`
--
DROP PROCEDURE IF EXISTS proc_get_total_news;

--
-- Drop procedure `proc_insert_news`
--
DROP PROCEDURE IF EXISTS proc_insert_news;

--
-- Drop procedure `proc_update_news`
--
DROP PROCEDURE IF EXISTS proc_update_news;

--
-- Drop table `news`
--
DROP TABLE IF EXISTS news;

--
-- Drop procedure `proc_delete_order`
--
DROP PROCEDURE IF EXISTS proc_delete_order;

--
-- Drop procedure `proc_get_order_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_order_by_id;

--
-- Drop procedure `proc_get_orders`
--
DROP PROCEDURE IF EXISTS proc_get_orders;

--
-- Drop procedure `proc_get_orders_filter`
--
DROP PROCEDURE IF EXISTS proc_get_orders_filter;

--
-- Drop procedure `proc_get_orders_history_id`
--
DROP PROCEDURE IF EXISTS proc_get_orders_history_id;

--
-- Drop procedure `proc_get_total_order`
--
DROP PROCEDURE IF EXISTS proc_get_total_order;

--
-- Drop procedure `proc_insert_order_payment`
--
DROP PROCEDURE IF EXISTS proc_insert_order_payment;

--
-- Drop procedure `proc_update_order`
--
DROP PROCEDURE IF EXISTS proc_update_order;

--
-- Drop table `order`
--
DROP TABLE IF EXISTS `order`;

--
-- Drop procedure `proc_get_OrderDetails`
--
DROP PROCEDURE IF EXISTS proc_get_OrderDetails;

--
-- Drop procedure `proc_get_orderDetails_by_OrderId`
--
DROP PROCEDURE IF EXISTS proc_get_orderDetails_by_OrderId;

--
-- Drop procedure `proc_get_orderDetails_filter`
--
DROP PROCEDURE IF EXISTS proc_get_orderDetails_filter;

--
-- Drop procedure `proc_get_procducts_top_selling`
--
DROP PROCEDURE IF EXISTS proc_get_procducts_top_selling;

--
-- Drop procedure `proc_get_total_orderDetail`
--
DROP PROCEDURE IF EXISTS proc_get_total_orderDetail;

--
-- Drop procedure `proc_insert_orderdetail`
--
DROP PROCEDURE IF EXISTS proc_insert_orderdetail;

--
-- Drop table `orderdetail`
--
DROP TABLE IF EXISTS orderdetail;

--
-- Drop procedure `proc_delete_product`
--
DROP PROCEDURE IF EXISTS proc_delete_product;

--
-- Drop procedure `proc_get_product_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_product_by_id;

--
-- Drop procedure `proc_get_products`
--
DROP PROCEDURE IF EXISTS proc_get_products;

--
-- Drop procedure `proc_get_products_filter`
--
DROP PROCEDURE IF EXISTS proc_get_products_filter;

--
-- Drop procedure `proc_get_total_product`
--
DROP PROCEDURE IF EXISTS proc_get_total_product;

--
-- Drop procedure `proc_insert_product`
--
DROP PROCEDURE IF EXISTS proc_insert_product;

--
-- Drop procedure `proc_update_product`
--
DROP PROCEDURE IF EXISTS proc_update_product;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Drop procedure `proc_delete_productcategory`
--
DROP PROCEDURE IF EXISTS proc_delete_productcategory;

--
-- Drop procedure `proc_get_productcategory_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_productcategory_by_id;

--
-- Drop procedure `proc_get_productCategory_home`
--
DROP PROCEDURE IF EXISTS proc_get_productCategory_home;

--
-- Drop procedure `proc_get_ProductCategorys`
--
DROP PROCEDURE IF EXISTS proc_get_ProductCategorys;

--
-- Drop procedure `proc_get_productCategorys_filter`
--
DROP PROCEDURE IF EXISTS proc_get_productCategorys_filter;

--
-- Drop procedure `proc_get_total_productCategory`
--
DROP PROCEDURE IF EXISTS proc_get_total_productCategory;

--
-- Drop procedure `proc_insert_productcategory`
--
DROP PROCEDURE IF EXISTS proc_insert_productcategory;

--
-- Drop procedure `proc_update_productcategory`
--
DROP PROCEDURE IF EXISTS proc_update_productcategory;

--
-- Drop table `productcategory`
--
DROP TABLE IF EXISTS productcategory;

--
-- Drop procedure `proc_delete_project`
--
DROP PROCEDURE IF EXISTS proc_delete_project;

--
-- Drop procedure `proc_get_project_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_project_by_id;

--
-- Drop procedure `proc_get_project_home`
--
DROP PROCEDURE IF EXISTS proc_get_project_home;

--
-- Drop procedure `proc_get_project_hot`
--
DROP PROCEDURE IF EXISTS proc_get_project_hot;

--
-- Drop procedure `proc_get_projects`
--
DROP PROCEDURE IF EXISTS proc_get_projects;

--
-- Drop procedure `proc_get_projects_filter`
--
DROP PROCEDURE IF EXISTS proc_get_projects_filter;

--
-- Drop procedure `proc_get_total_project`
--
DROP PROCEDURE IF EXISTS proc_get_total_project;

--
-- Drop procedure `proc_insert_project`
--
DROP PROCEDURE IF EXISTS proc_insert_project;

--
-- Drop procedure `proc_update_project`
--
DROP PROCEDURE IF EXISTS proc_update_project;

--
-- Drop table `project`
--
DROP TABLE IF EXISTS project;

--
-- Drop procedure `proc_delete_recruitment`
--
DROP PROCEDURE IF EXISTS proc_delete_recruitment;

--
-- Drop procedure `proc_get_recruitment_by_id`
--
DROP PROCEDURE IF EXISTS proc_get_recruitment_by_id;

--
-- Drop procedure `proc_get_recruitment_home`
--
DROP PROCEDURE IF EXISTS proc_get_recruitment_home;

--
-- Drop procedure `proc_get_recruitment_hot`
--
DROP PROCEDURE IF EXISTS proc_get_recruitment_hot;

--
-- Drop procedure `proc_get_recruitments`
--
DROP PROCEDURE IF EXISTS proc_get_recruitments;

--
-- Drop procedure `proc_get_recruitments_filter`
--
DROP PROCEDURE IF EXISTS proc_get_recruitments_filter;

--
-- Drop procedure `proc_get_total_recruitment`
--
DROP PROCEDURE IF EXISTS proc_get_total_recruitment;

--
-- Drop procedure `proc_insert_recruitment`
--
DROP PROCEDURE IF EXISTS proc_insert_recruitment;

--
-- Drop procedure `proc_update_recruitment`
--
DROP PROCEDURE IF EXISTS proc_update_recruitment;

--
-- Drop table `recruitment`
--
DROP TABLE IF EXISTS recruitment;

--
-- Drop procedure `proc_get_contact_filter`
--
DROP PROCEDURE IF EXISTS proc_get_contact_filter;

--
-- Drop procedure `proc_get_contacts`
--
DROP PROCEDURE IF EXISTS proc_get_contacts;

--
-- Drop procedure `proc_insert_contact`
--
DROP PROCEDURE IF EXISTS proc_insert_contact;

--
-- Drop table `contact`
--
DROP TABLE IF EXISTS contact;

--
-- Set default database
--
USE webnoithat;

--
-- Create table `contact`
--
CREATE TABLE contact (
  ContactId char(36) NOT NULL DEFAULT '',
  ContactName varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ContactEmail varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ContactPhone varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ContactReminder varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  PRIMARY KEY (ContactId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_insert_contact`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_contact ()
BEGIN
  INSERT INTO contact (ContactId, ContactName, ContactEmail, ContactPhone, ContactReminder, CreatedDate, ModifiedDate)
    VALUES (UUID(), _ContactName, _ContactEmail, _ContactPhone, _ContactReminder, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_contacts`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_contacts ()
BEGIN
  SELECT
    *
  FROM contact c;
END
$$

--
-- Create procedure `proc_get_contact_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_contact_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    c.ContactId,
    c.ContactName,
    c.ContactEmail,
    c.ContactPhone,
    c.ContactReminder,
    c.CreatedDate,
    c.ModifiedDate
  FROM contact c
  WHERE (Fil IS NULL)
  OR (c.ContactName LIKE CONCAT('%', Fil, '%'))
  ORDER BY c.ModifiedDate DESC
  LIMIT start, PageSize;
END
$$

DELIMITER ;

--
-- Create table `recruitment`
--
CREATE TABLE recruitment (
  RecruitmentId char(36) NOT NULL,
  RecruitmentTitle varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'TiÃªu Ä‘á» tuyá»ƒn dá»¥ng',
  RecruitmentContent varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Ná»™i dung tuyá»ƒn dá»¥ng',
  LinkImage varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  RecruitmentHome int DEFAULT NULL,
  RecruitmentHot int DEFAULT NULL,
  PRIMARY KEY (RecruitmentId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_recruitment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_recruitment (IN _RecruitmentId char(36), IN _RecruitmentTitle varchar(255), IN _RecruitmentContent varchar(1000), IN _LinkImage varchar(255))
BEGIN
  UPDATE recruitment r
  SET r.RecruitmentTitle = _RecruitmentTitle,
      r.RecruitmentContent = _RecruitmentContent,
      r.LinkImage = _LinkImage,
      r.ModifiedDate = NOW()
  WHERE r.RecruitmentId = _RecruitmentId;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_recruitment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_recruitment (_RecruitmentTitle varchar(255), _RecruitmentContent varchar(255), _LinkImage varchar(255))
BEGIN
  INSERT INTO recruitment (RecruitmentId, RecruitmentTitle, RecruitmentContent, LinkImage, CreatedDate, ModifiedDate)
    VALUES (UUID(), _RecruitmentTitle, _RecruitmentContent, _LinkImage, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_total_recruitment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_recruitment (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM recruitment r
  WHERE (Fil IS NULL)
  OR (r.RecruitmentTitle LIKE CONCAT('%', Fil, '%'));
END
$$

--
-- Create procedure `proc_get_recruitments_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_recruitments_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    *
  FROM recruitment r
  WHERE (Fil IS NULL)
  OR (r.RecruitmentTitle LIKE CONCAT('%', Fil, '%'))
  ORDER BY r.ModifiedDate DESC
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_recruitments`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_recruitments ()
BEGIN
  SELECT
    *
  FROM recruitment r;
END
$$

--
-- Create procedure `proc_get_recruitment_hot`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_recruitment_hot ()
BEGIN
  SELECT
    *
  FROM recruitment r
  WHERE r.RecruitmentHot = 1
  LIMIT 6;

END
$$

--
-- Create procedure `proc_get_recruitment_home`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_recruitment_home ()
BEGIN
  SELECT
    *
  FROM recruitment r
  WHERE r.RecruitmentHome = 1
  ORDER BY r.ModifiedDate DESC
  LIMIT 3;
END
$$

--
-- Create procedure `proc_get_recruitment_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_recruitment_by_id (IN _RecruitmentId char(36))
BEGIN
  SELECT
    *
  FROM recruitment r
  WHERE r.RecruitmentId = _RecruitmentId;
END
$$

--
-- Create procedure `proc_delete_recruitment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_recruitment (IN _RecruitmentId varchar(255))
BEGIN
  IF EXISTS (SELECT
        *
      FROM recruitment r
      WHERE r.RecruitmentId = _RecruitmentId) THEN
    DELETE
      FROM recruitment
    WHERE recruitment.RecruitmentId = _RecruitmentId;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

--
-- Create table `project`
--
CREATE TABLE project (
  ProjectId char(36) NOT NULL,
  ProjectTitle varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'TiÃªu Ä‘á» dá»± Ã¡n',
  ProjectContent varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Ná»™i dung dá»± Ã¡n',
  CreatedDate date DEFAULT NULL COMMENT 'NgÃ y táº¡o',
  LinkImage varchar(255) DEFAULT NULL COMMENT 'Link áº£nh',
  ModifiedDate date DEFAULT NULL,
  ProjectHome int DEFAULT NULL,
  ProjectHot int DEFAULT NULL,
  PRIMARY KEY (ProjectId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_project`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_project (IN _ProjectId char(36), IN _ProjectTitle varchar(255), IN _ProjectContent varchar(1000), IN _LinkImage varchar(255), IN _ProjectHome varchar(255))
BEGIN
  UPDATE project p
  SET p.ProjectId = _ProjectId,
      p.ProjectTitle = _ProjectTitle,
      p.ProjectContent = _ProjectContent,
      p.LinkImage = _LinkImage,
      p.ProjectHome = _ProjectHome,
      p.ModifiedDate = NOW()
  WHERE p.ProjectId = _ProjectId;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_project`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_project (IN _ProjectTitle varchar(255), IN _ProjectContent varchar(1000), IN _LinkImage varchar(255), IN _ProjectHome varchar(255))
BEGIN
  INSERT INTO project (ProjectId, ProjectTitle, ProjectContent, LinkImage, ProjectHome, CreatedDate, ModifiedDate)
    VALUES (UUID(), _ProjectTitle, _ProjectContent, _LinkImage, _ProjectHome, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_total_project`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_project (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM project p
  WHERE (Fil IS NULL)
  OR (p.ProjectTitle LIKE CONCAT('%', Fil, '%'));
END
$$

--
-- Create procedure `proc_get_projects_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_projects_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    *
  FROM project p
  WHERE (Fil IS NULL)
  OR (p.ProjectTitle LIKE CONCAT('%', Fil, '%'))
  ORDER BY p.ModifiedDate DESC
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_projects`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_projects ()
BEGIN
  SELECT
    *
  FROM project p;
END
$$

--
-- Create procedure `proc_get_project_hot`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_project_hot ()
BEGIN
  SELECT
    *
  FROM project p
  WHERE p.ProjectHot = 1
  LIMIT 6;

END
$$

--
-- Create procedure `proc_get_project_home`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_project_home ()
BEGIN
  SELECT
    *
  FROM project p
  WHERE p.ProjectHome = 1
  LIMIT 4;

END
$$

--
-- Create procedure `proc_get_project_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_project_by_id (IN _ProjectId char(36))
BEGIN
  SELECT
    *
  FROM project p
  WHERE p.ProjectId = _ProjectId;
END
$$

--
-- Create procedure `proc_delete_project`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_project (IN _ProjectId char(36))
BEGIN
  IF EXISTS (SELECT
        *
      FROM project p
      WHERE p.ProjectId = _ProjectId) THEN
    DELETE
      FROM project
    WHERE project.ProjectId = _ProjectId;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

--
-- Create table `productcategory`
--
CREATE TABLE productcategory (
  ProductCategoryId char(36) NOT NULL COMMENT 'id',
  ProductCategoryName varchar(255) DEFAULT NULL COMMENT 'TÃªn danh má»¥c sáº£n pháº©m',
  ProductCategoryDescription varchar(255) DEFAULT NULL COMMENT 'MÃ´ táº£ danh má»¥c sáº£n pháº©m',
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ProductCategoryImage varchar(255) DEFAULT NULL,
  ProductCategoryHome int DEFAULT NULL,
  PRIMARY KEY (ProductCategoryId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_productcategory`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_productcategory (IN _ProductCategoryId char(36), IN _ProductCategoryName varchar(255), IN _ProductCategoryDescription varchar(255), IN _ProductCategoryImage varchar(255), IN _ProductCategoryHome int)
BEGIN
  UPDATE productcategory p
  SET p.ProductCategoryName = _ProductCategoryName,
      p.ProductCategoryDescription = _ProductCategoryDescription,
      p.ProductCategoryImage = _ProductCategoryImage,
      p.ProductCategoryHome = _ProductCategoryHome,
      p.ModifiedDate = NOW()
  WHERE p.ProductCategoryId = _ProductCategoryId;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_productcategory`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_productcategory (IN _ProductCategoryName varchar(255), IN _ProductCategoryDescription varchar(255), IN _ProductCategoryImage varchar(255), IN _ProductCategoryHome int)
BEGIN
  INSERT INTO productcategory (ProductCategoryId, ProductCategoryName, ProductCategoryDescription, ProductCategoryImage, ProductCategoryHome, CreatedDate, ModifiedDate)
    VALUES (UUID(), _ProductCategoryName, _ProductCategoryDescription, _ProductCategoryImage, _ProductCategoryHome, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_total_productCategory`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_productCategory (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM productcategory p
  WHERE (Fil IS NULL)
  OR (p.ProductCategoryName LIKE CONCAT('%', Fil, '%'));
END
$$

--
-- Create procedure `proc_get_productCategorys_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_productCategorys_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    *
  FROM productcategory p
  WHERE (Fil IS NULL)
  OR (p.ProductCategoryName LIKE CONCAT('%', Fil, '%'))
  ORDER BY p.ModifiedDate DESC
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_ProductCategorys`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_ProductCategorys ()
BEGIN
  SELECT
    *
  FROM ProductCategory;
END
$$

--
-- Create procedure `proc_get_productCategory_home`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_productCategory_home ()
BEGIN
  SELECT
    *
  FROM productcategory p
  WHERE p.ProductCategoryHome = 1
  LIMIT 6;

END
$$

--
-- Create procedure `proc_get_productcategory_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_productcategory_by_id (IN _ProductCategoryId char(36))
BEGIN
  SELECT
    *
  FROM productcategory p
  WHERE p.ProductCategoryId = _ProductCategoryId;
END
$$

--
-- Create procedure `proc_delete_productcategory`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_productcategory (IN _ProductCategoryId char(36))
BEGIN
  IF EXISTS (SELECT
        *
      FROM productcategory p
      WHERE p.ProductCategoryId = _ProductCategoryId) THEN
    DELETE
      FROM productcategory
    WHERE productcategory.ProductCategoryId = _ProductCategoryId;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

--
-- Create table `product`
--
CREATE TABLE product (
  ProductId char(36) NOT NULL DEFAULT '',
  ProductName varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ProductDimensions varchar(255) DEFAULT NULL,
  ProductMaterial varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  ProductManufacturer varchar(255) DEFAULT NULL,
  ProductColor int DEFAULT NULL,
  ProductOriginalPrice double DEFAULT NULL,
  ProductSalePrice double DEFAULT NULL,
  ProductDescriptionShort varchar(255) DEFAULT NULL,
  ProductDescription varchar(255) DEFAULT NULL,
  ProductEvaluate double DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ProductCategoryId char(36) DEFAULT NULL,
  ProductImage varchar(255) DEFAULT NULL,
  PRIMARY KEY (ProductId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 910,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_product (IN _ProductId char(36), IN _ProductName varchar(255), IN _ProductDimensions varchar(255), IN _ProductMaterial varchar(255),
IN _ProductManufacturer varchar(255), IN _ProductColor int, IN _ProductOriginalPrice double, IN _ProductSalePrice double,
IN _ProductDescriptionShort varchar(255), IN _ProductDescription varchar(255), IN _ProductEvaluate double,
IN _ProductCategoryId char(36), IN _ProductImage varchar(255))
BEGIN
  UPDATE product p
  SET p.ProductId = _ProductId,
      p.ProductName = _ProductName,
      p.ProductDimensions = _ProductDimensions,
      p.ProductMaterial = _ProductMaterial,
      p.ProductManufacturer = _ProductManufacturer,
      p.ProductColor = _ProductColor,
      p.ProductOriginalPrice = _ProductOriginalPrice,
      p.ProductSalePrice = _ProductSalePrice,
      p.ProductDescriptionShort = _ProductDescriptionShort,
      p.ProductDescription = _ProductDescription,
      p.ProductEvaluate = _ProductEvaluate,
      p.ProductCategoryId = _ProductCategoryId,
      p.ProductImage = _ProductImage,
      p.ModifiedDate = NOW()
  WHERE p.ProductId = _ProductId;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_product (IN _ProductName varchar(255), IN _ProductDimensions varchar(255), IN _ProductMaterial varchar(255), IN _ProductManufacturer varchar(255), IN _ProductColor int, IN _ProductOriginalPrice double, IN _ProductSalePrice double, IN _ProductDescriptionShort varchar(255), IN _ProductDescription varchar(255), IN _ProductEvaluate double, IN _ProductCategoryId char(36), IN _ProductImage varchar(255))
BEGIN
  INSERT INTO product (ProductId, ProductName, ProductDimensions, ProductMaterial, ProductManufacturer, ProductColor, ProductOriginalPrice, ProductSalePrice, ProductDescriptionShort, ProductDescription, ProductEvaluate, ProductCategoryId, ProductImage, CreatedDate, ModifiedDate)
    VALUES (UUID(), _ProductName, _ProductDimensions, _ProductMaterial, _ProductManufacturer, _ProductColor, _ProductOriginalPrice, _ProductSalePrice, _ProductDescriptionShort, _ProductDescription, _ProductEvaluate, _ProductCategoryId, _ProductImage, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_total_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_product (IN Fil nvarchar(255), IN CategoryId char(36), IN Price double)
BEGIN
  IF (Price > 0) THEN
    SELECT
      COUNT(*)
    FROM product p
    WHERE ((Fil IS NULL)
    OR (p.ProductName LIKE CONCAT('%', Fil, '%')))
    AND ((CategoryId IS NULL)
    OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
    AND (p.ProductSalePrice / 1000000 <= Price);
  END IF;
  IF (Price = 0) THEN
    SELECT
      COUNT(*)
    FROM product p
    WHERE ((Fil IS NULL)
    OR (p.ProductName LIKE CONCAT('%', Fil, '%')))
    AND ((CategoryId IS NULL)
    OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')));
  END IF;
END
$$

--
-- Create procedure `proc_get_products_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_products_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255), IN SortStatus int, IN FieldSort varchar(30), IN CategoryId char(36), IN Price double)
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;
  IF (Price > 0) THEN
    IF (SortStatus = 1) THEN
      SELECT
        *
      FROM product p
      WHERE ((Fil IS NULL)
      OR (p.ProductName LIKE CONCAT('%', Fil, '%'))
      OR (p.ProductCategoryId LIKE CONCAT('%', Fil, '%')))
      AND ((CategoryId IS NULL)
      OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
      AND (p.ProductSalePrice / 1000000 <= Price)

      ORDER BY p.ProductSalePrice DESC
      LIMIT start, PageSize;
    END IF;
    IF (SortStatus = 2) THEN
      SELECT
        *
      FROM product p
      WHERE ((Fil IS NULL)
      OR (p.ProductName LIKE CONCAT('%', Fil, '%')))
      AND ((CategoryId IS NULL)
      OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
      AND (p.ProductSalePrice / 1000000 <= Price)
      ORDER BY p.ProductSalePrice ASC
      LIMIT start, PageSize;
    END IF;
    IF (SortStatus != 1
      || SortStatus != 2
      || SortStatus = NULL) THEN
      SELECT
        *
      FROM product p
      WHERE ((Fil IS NULL)
      OR (p.ProductName LIKE CONCAT('%', Fil, '%')))
      AND ((CategoryId IS NULL)
      OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
      AND (p.ProductSalePrice / 1000000 <= Price)
      LIMIT start, PageSize;
    END IF;
  END IF;
  IF (Price = 0) THEN
    IF (SortStatus = 1) THEN
      SELECT
        *
      FROM product p
      WHERE ((Fil IS NULL)
      OR (p.ProductName LIKE CONCAT('%', Fil, '%'))
      OR (p.ProductCategoryId LIKE CONCAT('%', Fil, '%')))
      AND ((CategoryId IS NULL)
      OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
      ORDER BY p.ProductSalePrice DESC
      LIMIT start, PageSize;
    END IF;
    IF (SortStatus = 2) THEN
      SELECT
        *
      FROM product p
      WHERE ((Fil IS NULL)
      OR (p.ProductName LIKE CONCAT('%', Fil, '%')))
      AND ((CategoryId IS NULL)
      OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
      ORDER BY p.ProductSalePrice ASC
      LIMIT start, PageSize;
    END IF;
    IF (SortStatus != 1
      || SortStatus != 2
      || SortStatus = NULL) THEN
      SELECT
        *
      FROM product p
      WHERE ((Fil IS NULL)
      OR (p.ProductName LIKE CONCAT('%', Fil, '%')))
      AND ((CategoryId IS NULL)
      OR (p.ProductCategoryId LIKE CONCAT('%', CategoryId, '%')))
      ORDER BY p.ModifiedDate DESC
      LIMIT start, PageSize;
    END IF;
  END IF;
END
$$

--
-- Create procedure `proc_get_products`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_products ()
BEGIN
  SELECT
    *
  FROM product p;
END
$$

--
-- Create procedure `proc_get_product_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_product_by_id (IN _ProductId char(36))
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductId = _ProductId;
END
$$

--
-- Create procedure `proc_delete_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_product (IN _ProductId char(36))
BEGIN
  IF EXISTS (SELECT
        *
      FROM product p
      WHERE p.ProductId = _ProductId) THEN
    DELETE
      FROM product
    WHERE product.ProductId = _ProductId;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

--
-- Create table `orderdetail`
--
CREATE TABLE orderdetail (
  OrderId char(36) DEFAULT NULL,
  ProductId char(36) DEFAULT NULL,
  Amount int DEFAULT NULL,
  ProductName varchar(255) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_insert_orderdetail`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_orderdetail (IN OrderId char(36), IN ProductId char(36), IN Amount int, IN ProductName varchar(255))
BEGIN
  INSERT INTO OrderDetail
    VALUES (OrderId, ProductId, Amount, ProductName);
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_total_orderDetail`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_orderDetail (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM orderdetail o
  WHERE Fil IS NULL;
END
$$

--
-- Create procedure `proc_get_procducts_top_selling`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_procducts_top_selling (IN number int)
BEGIN
  SELECT
    p.*,
    SUM(o.Amount)
  FROM product p,
       orderdetail o
  WHERE p.ProductId = o.ProductId
  ORDER BY SUM(o.Amount) DESC LIMIT number;
END
$$

--
-- Create procedure `proc_get_orderDetails_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_orderDetails_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    *
  FROM orderdetail o
  WHERE (Fil IS NULL)
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_orderDetails_by_OrderId`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_orderDetails_by_OrderId (IN OrderId char(36))
BEGIN
  SELECT
    *
  FROM orderdetail o
  WHERE o.OrderId = OrderId;
END
$$

--
-- Create procedure `proc_get_OrderDetails`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_OrderDetails ()
BEGIN
  SELECT
    *
  FROM OrderDetail;
END
$$

DELIMITER ;

--
-- Create table `order`
--
CREATE TABLE `order` (
  UserId char(36) DEFAULT NULL,
  OrderId char(36) NOT NULL,
  CreatedDate datetime DEFAULT NULL COMMENT 'Ng?y t?o',
  ModifiedDate datetime DEFAULT NULL,
  FullName varchar(255) DEFAULT NULL,
  Address varchar(255) DEFAULT NULL,
  PhoneNumber varchar(255) DEFAULT NULL,
  PaymentMethods int DEFAULT NULL,
  Note varchar(255) DEFAULT NULL,
  UserName varchar(255) DEFAULT NULL,
  StatusOrder int DEFAULT NULL,
  PRIMARY KEY (OrderId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_order`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_order (IN _UserId char(36), IN _Order_id char(36))
BEGIN
  UPDATE `order` o
  SET o.UserId = _UserId,
      o.OrderId = _Order_id,
      o.ModifiedDate = NOW()
  WHERE o.OrderId = _Order_id;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_order_payment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_order_payment (IN UserId char(36), IN UserName varchar(255), IN FullName varchar(255), IN Address varchar(255), IN PhoneNumber varchar(255), IN PaymentMethods int, IN Note varchar(255), IN StatusOrder int)
BEGIN
  DECLARE id char(36);
  INSERT INTO `order` (UserId, OrderId, CreatedDate, ModifiedDate, FullName, Address, PhoneNumber, PaymentMethods, Note, UserName, StatusOrder)
    VALUE (UserId, UUID(), NOW(), NOW(), FullName, Address, PhoneNumber, PaymentMethods, Note, UserName, StatusOrder);
  SELECT
    *
  FROM `order` o
  ORDER BY o.ModifiedDate DESC LIMIT 1;
END
$$

--
-- Create procedure `proc_get_total_order`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_order (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM `order` o
  WHERE Fil IS NULL;
END
$$

--
-- Create procedure `proc_get_orders_history_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_orders_history_id (IN UserId char(36), IN PageIndex int, IN PageSize int)
BEGIN
  DECLARE start int;
  DECLARE end int;
  DECLARE odID char(36);
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;
  SET odID = (SELECT
      o.OrderId
    FROM `order` o
    WHERE o.UserId = UserId);

  SELECT
    *
  FROM orderdetail od
    INNER JOIN `order` o
      ON od.OrderId = odID
  LIMIT start, PageSize;



END
$$

--
-- Create procedure `proc_get_orders_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_orders_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    *
  FROM `order` o
  WHERE (Fil IS NULL)
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_orders`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_orders ()
BEGIN
  SELECT
    *
  FROM webnoithat.`order` o;
END
$$

--
-- Create procedure `proc_get_order_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_order_by_id (IN _OrderId char(36))
BEGIN
  SELECT
    *
  FROM `order` o
  WHERE o.OrderId = _OrderId;
END
$$

--
-- Create procedure `proc_delete_order`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_order (IN _Order_id char(36))
BEGIN
  IF EXISTS (SELECT
        *
      FROM `order` o
      WHERE o.OrderId = _Order_id) THEN
    DELETE
      FROM `order`
    WHERE `order`.OrderId = _Order_id;
    DELETE
      FROM orderdetail
    WHERE orderdetail.Order_id = _Order_id;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

--
-- Create table `news`
--
CREATE TABLE news (
  NewsId char(36) NOT NULL,
  NewsTitle varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'TiÃªu Ä‘á» tin tá»©c',
  NewsContent varchar(5000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Ná»™i dung tin tá»©c',
  LinkImage varchar(255) DEFAULT NULL COMMENT 'Link áº£nh',
  NewsHot int DEFAULT NULL COMMENT 'Tin tá»©c hot',
  NewsProduct int DEFAULT NULL COMMENT 'Tin tá»©c sáº£n pháº©m',
  NewsSale int DEFAULT NULL COMMENT 'Tin tá»©c khuyáº¿n mÃ£i',
  NewsEvent int DEFAULT NULL COMMENT 'Tin tá»©c sá»± kiá»‡n',
  NewsHome int DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  PRIMARY KEY (NewsId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_news`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_news (IN _NewsId char(36), IN _NewsTitle varchar(255), IN _NewsContent varchar(5000), IN _LinkImage varchar(255), IN _NewsHot int, IN _NewsProduct int, IN _NewsSale int, IN _NewsEvent int, IN _NewsHome int)
BEGIN
  UPDATE news n
  SET n.NewsId = _NewsId,
      n.NewsTitle = _NewsTitle,
      n.NewsContent = _NewsContent,
      n.LinkImage = _LinkImage,
      n.NewsHot = _NewsHot,
      n.NewsProduct = _NewsProduct,
      n.NewsSale = _NewsSale,
      n.NewsEvent = _NewsEvent,
      n.NewsHome = _NewsHome,
      n.ModifiedDate = NOW()
  WHERE n.NewsId = _NewsId;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_news`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_news (IN _NewsTitle varchar(255), IN _NewsContent varchar(5000), IN _LinkImage varchar(255), IN _NewsHot int, IN _NewsProduct int, IN _NewsSale int, IN _NewsEvent int, IN _NewsHome int)
BEGIN
  INSERT INTO news (NewsId, NewsTitle, NewsContent, LinkImage, NewsHot, NewsProduct, NewsSale, NewsEvent, NewsHome, CreatedDate, ModifiedDate)
    VALUES (UUID(), _NewsTitle, _NewsContent, _LinkImage, _NewsHot, _NewsProduct, _NewsSale, _NewsEvent, _NewsHome, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_total_news`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_news (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM news n
  WHERE (Fil IS NULL)
  OR (n.NewsTitle LIKE CONCAT('%', Fil, '%'));
END
$$

--
-- Create procedure `proc_get_newss_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_newss_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;
  SELECT
    *
  FROM news n
  WHERE (Fil IS NULL)
  OR (n.NewsTitle LIKE CONCAT('%', Fil, '%'))
  ORDER BY n.ModifiedDate DESC
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_newss`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_newss ()
BEGIN
  SELECT
    *
  FROM news n;
END
$$

--
-- Create procedure `proc_get_news_sale`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_news_sale ()
BEGIN
  SELECT
    *
  FROM news n
  WHERE n.NewsSale = 1
  ORDER BY n.ModifiedDate DESC
  LIMIT 6;
END
$$

--
-- Create procedure `proc_get_news_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_news_product ()
BEGIN
  SELECT
    *
  FROM news n
  WHERE n.NewsProduct = 1
  ORDER BY n.ModifiedDate DESC
  LIMIT 6;
END
$$

--
-- Create procedure `proc_get_news_hot`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_news_hot ()
BEGIN
  SELECT
    *
  FROM news n
  WHERE n.NewsHot = 1
  ORDER BY n.ModifiedDate DESC
  LIMIT 6;
END
$$

--
-- Create procedure `proc_get_news_home`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_news_home ()
BEGIN
  SELECT
    *
  FROM news n
  WHERE n.NewsHome = 1
  LIMIT 3;

END
$$

--
-- Create procedure `proc_get_news_event`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_news_event ()
BEGIN
  SELECT
    *
  FROM news n
  WHERE n.NewsEvent = 1
  ORDER BY n.ModifiedDate DESC
  LIMIT 6;
END
$$

--
-- Create procedure `proc_get_news_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_news_by_id (IN _NewsId char(36))
BEGIN
  SELECT
    *
  FROM news n
  WHERE n.NewsId = _NewsId;
END
$$

--
-- Create procedure `proc_delete_news`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_news (IN _NewsId char(36))
BEGIN
  IF EXISTS (SELECT
        *
      FROM news n
      WHERE n.NewsId = _NewsId) THEN
    DELETE
      FROM news
    WHERE news.NewsId = _NewsId;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

--
-- Create table `user`
--
CREATE TABLE user (
  UserId char(36) NOT NULL DEFAULT '',
  UserName varchar(255) DEFAULT NULL COMMENT 'TÃ i khoáº£n',
  Password varchar(255) DEFAULT NULL COMMENT 'Máº­t kháº©u',
  FullName varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'TÃªn ngÆ°á»i dÃ¹ng',
  Address varchar(255) DEFAULT NULL COMMENT 'Äá»‹a chá»‰',
  PhoneNumber varchar(100) DEFAULT NULL COMMENT 'SDT',
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  Role int DEFAULT NULL,
  id bigint NOT NULL,
  age int DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  occupation varchar(255) DEFAULT NULL,
  PRIMARY KEY (UserId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `proc_update_user`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_update_user (IN _UserId char(36), IN _UserName varchar(255), IN _Password varchar(255), IN _FullName nvarchar(255), IN _Address nvarchar(255), IN _PhoneNumber nvarchar(100))
BEGIN
  UPDATE user u
  SET u.UserName = _UserName,
      u.Password = _Password,
      u.FullName = _FullName,
      u.Address = _Address,
      u.PhoneNumber = _PhoneNumber,
      u.ModifiedDate = NOW()
  WHERE u.UserId = _UserId;
  SELECT
    1;
END
$$

--
-- Create procedure `proc_insert_user`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_insert_user (IN _UserName varchar(255), IN _Password varchar(255), _FullName nvarchar(255), _Address nvarchar(255), _PhoneNumber nvarchar(100))
BEGIN
  INSERT INTO USER (UserId, UserName, Password, FullName, Address, PhoneNumber, CreatedDate, ModifiedDate)
    VALUES (UUID(), _UserName, _Password, _FullName, _Address, _PhoneNumber, NOW(), NOW());
  SELECT
    1;
END
$$

--
-- Create procedure `proc_get_user_by_username`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_user_by_username (IN _UserName varchar(255))
BEGIN
  SELECT
    *
  FROM user u
  WHERE u.UserName = _UserName;
END
$$

--
-- Create procedure `proc_get_user_by_id`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_user_by_id (IN _UserId char(36))
BEGIN
  SELECT
    *
  FROM user u
  WHERE u.UserId = _UserId;

END
$$

--
-- Create procedure `proc_get_users_filter`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_users_filter (IN PageIndex int, IN PageSize int, IN Fil nvarchar(255))
BEGIN
  DECLARE start int;
  DECLARE end int;
  SET START = ((PageIndex - 1) * PageSize);
  SET end = ((PageIndex - 1) * PageSize) + PageSize;

  SELECT
    *
  FROM user u
  WHERE (Fil IS NULL)
  OR (u.UserName LIKE CONCAT('%', Fil, '%')
  OR u.FullName LIKE CONCAT('%', Fil, '%')
  OR u.Address LIKE CONCAT('%', Fil, '%'))
  ORDER BY u.ModifiedDate DESC
  LIMIT start, PageSize;
END
$$

--
-- Create procedure `proc_get_users`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_users ()
BEGIN
  SELECT
    *
  FROM user u;
END
$$

--
-- Create procedure `proc_get_total_user`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_get_total_user (IN Fil nvarchar(255))
BEGIN
  SELECT
    COUNT(*)
  FROM user u
  WHERE (Fil IS NULL)
  OR (u.UserName LIKE CONCAT('%', Fil, '%')
  OR u.FullName LIKE CONCAT('%', Fil, '%')
  OR u.Address LIKE CONCAT('%', Fil, '%'));
END
$$

--
-- Create procedure `proc_delete_user`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_delete_user (IN _UserId char(36))
BEGIN
  IF EXISTS (SELECT
        *
      FROM user
      WHERE USER.UserId = _UserId) THEN
    DELETE
      FROM user
    WHERE user.UserId = _UserId;
    SELECT
      1;
  ELSE
    SELECT
      0;


  END IF;
END
$$

DELIMITER ;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('0530d44e-34d9-11ec-9f32-b00cd19df262', 'dat123456', '123456', 'dat', 'hn', '111111111', '2021-10-24 21:45:24', '2021-10-24 21:52:58', 1, 0, NULL, NULL, NULL, NULL),
('0530d44e-34d9-11ec-9f32-b00cd19df263', 'dat1234567', '1234567', 'dat', '11', '1111111111', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 2, 0, NULL, NULL, NULL, NULL),
('1253c55e-11ef-47d2-939c-f8af2ab5b47e', 'vanthanh1404', 'df1996', 'Vũ Văn Thanh', 'Gia Lai', '5906124672', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('18e5b1be-21ba-4e13-968a-51874c5fe309', 'hongduy1306', 'mf1996', 'Nguyễn Phong Hồng Duy', 'Gia Lai', '8280254087', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('1efc8044-1b43-4cb8-abf3-57464c534b02', 'xuantruong2804', 'mf1995', 'Lương Xuân Trường', 'Gia Lai', '4408111800', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('2a2f1b60-d664-403a-ac9e-695b90f6af9d', 'vanlam1308', 'gk1993', 'Đặng Văn Lâm', 'Hải Phòng', '5373436906', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('2bcfae75-5ed6-43fb-9d1e-bfe29d479b6d', 'quanghai1204', 'mf1997', 'Nguyễn Quang Hải', 'Hà Nội', '3397771624', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('3e6d44e0-cc8b-4eee-aae2-d3a8beb881d9', 'vietanh0101', 'df1999', 'Bùi Hoàng Việt Anh', 'Hà Nội', '8347284399', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('695fd02b-6dae-4ba8-88e3-52f1d7c0851d', 'tuananh1605', 'mf1995', 'Nguyễn Tuấn Anh', 'Gia Lai', '9169844154', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('6d612f81-3147-11ec-b095-98e7430c3bbc', '123123', '12312', '12312', '1231', '12312', '2021-10-20 08:45:38', '2021-10-20 08:45:38', NULL, 0, NULL, NULL, NULL, NULL),
('6f043802-317d-11ec-a72c-b00cd19df262', '1111', '1111', '1111', '111', '1111', '2021-10-20 15:12:14', '2021-10-20 18:28:20', NULL, 0, NULL, NULL, NULL, NULL),
('7b6c584f-6b38-4070-84f3-a630ccff6ae1', 'ngochai1505', 'df1993', 'Quế Ngọc Hải', 'Hà Nội', '6558249931', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL),
('901b4dd7-5b87-49b8-84d6-0d7b8c19919d', 'tienlinh2010', 'fw1997', 'Nguyễn Tiến Linh', 'Bình Dương', '9332084427', '2021-09-19 00:00:00', '2021-09-19 00:00:00', NULL, 0, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table recruitment
--
INSERT INTO recruitment VALUES
('03f4118b-5894-4c4b-bcdf-c70c25def9cd', 'Tuyển dụng nhân viên bán hàng', 'Mô tả công việc\r\n- Hiểu rõ và thuộc tính năng, giá, ưu nhược điểm của sản phẩm, sản phẩm tương tự, sản phẩm của đối thủ cạnh tranh.\r\n- Thu nhập và đánh giá thông tin về cạnh tranh, về khách hàng và thị trường.\r\n- Tiếp xúc khách hàng và ghi nhận toàn bộ các thông tin của khách hàng trong báo cáo tiếp xúc khách hàng. Báo cáo nội dung tiếp xúc khách hàng trong ngày cho Trưởng phòng.\r\n- Theo dõi quá trình thanh lý hợp đồng, hỗ trợ phòng kế toán đốc thúc công nợ, chỉ xong trách nhiệm khi khách hàng đã thanh toán xong.\r\n- Tìm hiểu nhu cầu của khách hàng. Tìm kiếm khách hàng tiềm năng.', 'tuyendung1.png', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 1, 0),
('6e77f5cf-7614-4e80-a0bd-6b63dfc84e0b', 'TUYỂN DỤNG NHÂN VIÊN HÀNH CHÍNH VĂN PHÒNG', 'Mô tả công việc\r\n- Soạn thảo các văn bản chung của Công ty.\r\n- Thực hiện công tác BHXH, BHYT của Công ty đảm bảo việc tuân thủ đúng các chế độ chính sách liên quan và quyền lợi của người lao động\r\n- Theo dõi, kiểm soát tình hình biến động nhân lực, ký HĐTV, HĐLĐ trong toàn công ty.\r\n- Thực hiện một số nhiệm vụ khác theo yêu cầu của cấp trên.', 'tuyendung2.png', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 1, 1),
('958c9352-4280-4225-aa5b-2ce270f5d48f', 'TUYỂN DỤNG CÔNG NHÂN SẢN XUẤT', 'Mô tả công việc\r\n- Vị trí tuyển dụng: Công nhân sản xuất\r\n- Số lượng tuyển: 20 người (Nam), độ tuổi từ 20 đến 40.\r\n- Thời gian làm việc: Theo ca', 'tuyendung3.png', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 1, 1),
('f70194f3-dbef-4a3c-ba5f-27f20d6fc1dc', 'Tuyển dụng nhân viên IT', 'Đảm bảo hệ thống Website hoạt động thông suốt.', 'tuyendung4.png', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 0, 0);

-- 
-- Dumping data for table project
--
INSERT INTO project VALUES
('165bf5ba-abc6-422d-80a0-b219e0ee9fc6', 'NỘI THẤT CĂN HỘ CHUNG CƯ CAO CẤP – HOÀNG ĐẠO THÚY', 'Tại dự dự án căn hộ chung cư nhà anh Phương Việt Á Đông đã cải tạo không gian nội thất phòng khách, phòng thư giãn, phòng ăn, không gian bếp, phòng thờ và 4 phòng ngủ. Toàn bộ nội thất trong căn hộ được sử dụng gỗ óc chó tự nhiên sang trọng. Nội thất gỗ óc chó đang được giới thượng lưu ưa chuộng trong những năm gần đây. Đây là dòng gỗ được nhập khẩu từ Bắc Mỹ, có độ bền cao và hệ thống vân gỗ tự nhiên đa dạng, mang vẻ đẹp mộc mạc nhưng vô cùng sang trọng. Những món đồ nội thất được tạo nên từ gỗ óc chó luôn thu hút người xem ngay từ cái nhìn đầu tiên.', '2021-09-19', 'project1_new.png', NULL, 1, 0),
('bba6d0b9-e91e-4b20-94b7-14ba860d21bc', 'THI CÔNG THIẾT KẾ NỘI THẤT BIỆT THỰ HỒ XƯƠNG RỒNG', 'Khu đô thị Hồ Xương Rồng tọa lạc tại vị trí trung tâm thành phố Thái Nguyên (Công ty cổ phần Sông Đà 2 làm chủ đầu tư). Khu đô thị có hồ nước rộng 9ha. Đây là khu đô thị cao cấp, góp phần tạo ra một điểm nhấn quan trọng cho bức tranh đô thị Thái Nguyên. Gia đình  sở hữu ngôi biệt thự rộng 210m2 tại khu đô thị hồ xương rồng. Với mong muốn tất cả các thành viên trong gia đình được tận hưởng giây phút thư giãn thoải mái nhất trong chính ngôi nhà của mình. Gia chủ đã lựa chọn Việt Á Đông cho công trình thiết kế nội thất của gia đình cùng vật liệu chủ đạo là gỗ óc chó.', '2021-09-19', 'project2_new.png', NULL, 1, 0),
('e9a74c05-9db2-46cb-b792-a0c8aed8f314', 'THIẾT KẾ NỘI THẤT GỖ ÓC CHÓ TẠI BIỆT THỰ ĐẶNG XÁ', 'Trong kiến trúc nhà ở biệt thự là không gian đẳng cấp nhất, được nhiều người mơ ước nhất. Vì vậy, các gia chủ thường rất kỹ tính trong việc lựa chọn đơn vị thiết kế nội thất để trang hoàng cho ngôi biệt thự của gia đình. Để xứng tầm đẳng cấp cho căn biệt thự rộng 500m2 đã lựa chọn Việt Á Đông thi công thiết kế nội thất biệt thự bằng gỗ óc chó cho tổ ấm của gia đình. Mời quý vị cùng chiêm ngưỡng vẻ đẹp đẳng cấp nội thất gỗ óc chó đằng sau cánh cửa của gia đình được việt Á Đông thiết kế như thế nào nhé.', '2021-09-19', 'project3_new.png', NULL, 1, 1),
('eb9bf535-2393-44d8-81ef-df06f003ea5b', 'THIẾT KẾ NỘI THẤT GỖ ÓC CHÓ BIỆT THỰ LIỀN KỀ NGUYỄN TRÃI', 'Biệt thự liền kề gia đình có tổng diện tích 87m2. Được thiết kế thi công hoàn thiện bởi Nội thất Việt Á Đông. Toàn bộ thiết kế nội thất sử dụng vật liệu gỗ óc chó cao cấp nhập khẩu từ Bắc Mỹ. Mang đến không gian sang trọng, tiện nghi, hiện đại.', '2021-09-19', 'project4_new.png', NULL, 1, 1),
('f1852909-5f91-49ba-9b31-7b0b2c145123', 'THIẾT KẾ NỘI THẤT BIỆT THỰ GỖ GÕ ĐỎ LIDECO', 'Dự án nội thất biệt thự gỗ gõ đỏ tại Lideco được Việt Á Đông thi công thiết kế với phong cách tân cổ điển. Mang nét đẹp sang trọng. Gia chủ là một người yêu thích nội thất bằng gỗ tự nhiên nên toàn bộ nội thất đều được sử dụng bằng gỗ gõ đỏ.', '2021-09-19', 'project5_new.png', NULL, 0, 0);

-- 
-- Dumping data for table productcategory
--
INSERT INTO productcategory VALUES
('33757229-0b61-4e52-8415-752b6387f551', 'Trẻ em', 'Bàn ghế trẻ ăn', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-banghetreem.png', 1),
('6bcd08e4-eabe-49f2-ba24-6433a30a924c', 'Phòng ngủ', 'Tủ quần áo', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-tuquanao.png', 1),
('728bb108-c820-40f6-9f96-30434a486c02', 'Nhà bếp', 'Ghế ăn', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-ghean.png', 1),
('7a7b922a-2ccd-441d-8a38-c89746772fb4', 'Phòng ngủ', 'Giường', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-giuong.png', 1),
('80796201-d22b-4630-9727-0babfbcfb4e9', 'Sàn gỗ', 'Sàn gỗ tự nhiên', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-sango.png', 1),
('d12fe84e-558b-4843-9e5f-51310b05feb4', 'Nhà bếp', 'Bộ bàn ăn', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-banan.png', 1),
('fa6423d6-c959-482c-9d24-bb27e91b946d', 'Phòng khách', 'Bộ ghế Sofa', '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'loai-sp-sofa.png', 0);

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
('04c7f523-39b2-410f-9a34-c23e7ef35bdb', 'Bộ bàn ăn 4 ghế gỗ Sồi', 'Chi tiết xem sản phẩm', 'Gỗ sồi', 'Gemmy wood', 20114181, 33000000, 28900000, 'Bộ bàn ăn 4 ghế gỗ Sồi', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'd12fe84e-558b-4843-9e5f-51310b05feb4', 'table1.png'),
('1b4d6f69-167d-420f-94e6-bb0c0f7269b8', 'Giường ngủ gỗ Lim', 'Chiều cao đầu giường: 110 cm\r\nChiều cao chân giường: 60 cm\r\nChiều dài: 200 cm\r\nChiều rộng: 180 cm', 'Gỗ Lim', 'Gemmy wood', 956956, 46000000, 35900000, 'Giường ngủ gỗ Lim', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '7a7b922a-2ccd-441d-8a38-c89746772fb4', 'giuong2.png'),
('2d60bfe0-77a6-4773-a943-da0807aa71df', 'Bộ bàn ăn 4 ghế gỗ thông', 'Chi tiết xem sản phẩm', 'Gỗ thông', 'Gemmy wood', 19314485, 7900000, 5900000, 'Bộ bàn ăn 4 ghế gỗ thông', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'd12fe84e-558b-4843-9e5f-51310b05feb4', 'table2_1.png'),
('4604dbc5-c51c-420b-a5d3-647143f3e3da', 'Ghế thư giãn trẻ em', 'Chiều rộng : 47 cm\r\n\r\nĐộ sâu : 56 cm\r\n\r\nChiều cao : 68 cm\r\n\r\nChiều rộng ghế : 38 cm\r\n\r\nChiều sâu ghế : 36 cm\r\n\r\nChiều cao ghế : 24 cm', 'Gỗ thông', 'Gemmy wood', 19314485, 1450000, 1200000, 'Ghế thư giãn trẻ em', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '33757229-0b61-4e52-8415-752b6387f551', 'sp-ghe-tre-em-1.png'),
('4af5647e-3f57-4d72-960f-6eafca4046a0', 'Bộ bàn ăn gỗ keo 6 ghế', 'Chi tiết xem sản phẩm', 'Gỗ keo', 'Gemmy wood', 19514483, 13900000, 10900000, 'Bộ bàn ăn gỗ keo 6 ghế', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'd12fe84e-558b-4843-9e5f-51310b05feb4', 'table3_1.png'),
('536e528a-df82-43a2-95e5-9e8c52b49924', 'Bộ ghế Sofa gỗ Óc chó', 'Ghế sofa ba chỗ:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 210 cm\r\n\r\nGhế sofa đơn:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 79 cm\r\n\r\nBàn:\r\nChiều cao: 45.5 cm\r\nChiều dài: 122 cm\r\nChiều rộng: 60 cm', 'Gỗ óc chó', 'Gemmy wood', 956956, 120500000, 101000000, 'Bộ ghế Sofa gỗ Óc chó', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'fa6423d6-c959-482c-9d24-bb27e91b946d', 'sofa2.png'),
('701ffd83-dff0-4d98-a8e0-6caa873400bf', 'Bộ giường đôi gỗ keo', 'Chiều cao đầu giường: 102 cm\r\nChiều cao chân giường: 61.5 cm\r\nChiều dài tối đa: 210 cm\r\nChiều rộng tối đa: 180 cm', 'Gỗ keo', 'Gemmy wood', 253242134, 19900000, 15900000, 'Bộ giường đôi gỗ keo', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '7a7b922a-2ccd-441d-8a38-c89746772fb4', 'giuong3.png'),
('7bc0d460-08f9-4c30-8c02-6bdde1a84fa3', 'Bộ ghế Sofa gỗ Teak', 'Ghế sofa ba chỗ:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 210 cm\r\n\r\nSofa hai chỗ:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 145 cm\r\n\r\nGhế sofa đơn:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 79 cm', 'Gỗ Teak', 'Gemmy wood', 19414485, 29900000, 22600000, 'Bộ ghế Sofa gỗ Teak', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'fa6423d6-c959-482c-9d24-bb27e91b946d', 'sofa4.png'),
('7ef663da-5c24-4064-a30c-72fae77b6c52', 'Ghế ăn gỗ Óc chó sang trọng', 'Rộng: 48 cm\r\nSâu: 50 cm\r\nCao: 83 cm', 'Gỗ óc chó', 'Gemmy wood', 19414485, 1370000, 1150000, 'Ghế ăn gỗ Óc chó sang trọng', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '728bb108-c820-40f6-9f96-30434a486c02', 'sp-ghe-an-go-oc-cho-1.png'),
('8a34ff09-aceb-4f98-8ecf-c3ef0dfe5065', 'Tủ quần áo 3 cánh', 'Chiều sâu: 53 cm\r\nChiều rộng: 147 cm\r\nChiều cao: 224 cm', 'Gỗ óc chó', 'Gemmy wood', 987049, 26500000, 21900000, 'Tủ quần áo 3 cánh', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '6bcd08e4-eabe-49f2-ba24-6433a30a924c', 'sp-tu-1.png'),
('a1e584a5-4845-4b9d-8887-c0ef25ce7c5e', 'Bàn ghế trẻ em BE001', 'Kích thước bàn:\r\n\r\nChiều dài : 83 cm\r\n\r\nChiều rộng : 58 cm\r\n\r\nChiều cao : 48 cm\r\n\r\nKích thước ghế:\r\n\r\nChiều rộng : 24 cm\r\n\r\nĐộ sâu : 24 cm\r\n\r\nChiều cao ghế : 28 cm\r\n\r\nTối đa tải : 35 kg', 'Gỗ thông', 'Gemmy wood', 19314485, 2700000, 2150000, 'Bàn ghế trẻ em BE001', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '33757229-0b61-4e52-8415-752b6387f551', 'sp-ghe-tre-em-2.png'),
('aa80041c-a5d3-4e49-8132-477554221978', 'Bộ ghế Sofa gỗ Mun', 'Ghế sofa ba chỗ:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 210 cm\r\n\r\nSofa hai chỗ:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 145 cm\r\n\r\nGhế sofa đơn:\r\nChiều cao: 72 cm\r\nChiều sâu: 75 cm\r\nChiều rộng: 79 cm', 'Gỗ mun', 'Gemmy wood', 1584324, 42200000, 35900000, 'Bộ ghế Sofa gỗ Mun', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'fa6423d6-c959-482c-9d24-bb27e91b946d', 'sofa3.png'),
('ae6536c6-45c0-45c5-a7d7-b4aedcc5c1e6', 'Sàn gỗ keo', 'Rộng: 20 cm\r\nDày: 1 cm\r\nDài: 80 cm', 'Gỗ keo', 'Gemmy wood', 253242134, 1400000, 1050000, 'Sàn gỗ keo', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '80796201-d22b-4630-9727-0babfbcfb4e9', 'san-go-keo.png'),
('b24ecb98-e9ba-4920-ab89-365c8e12076f', 'Bộ tủ quần áo gỗ thông', 'Tủ 3 đầu giường 3 ngăn kéo:\r\nChiều cao: 60 cm\r\nChiều rộng: 48 cm\r\nChiều sâu:  40 cm\r\n\r\nTủ 5 ngăn kéo:\r\nChiều cao: 98 cm\r\nChiều rộng: 93 cm\r\nChiều sâu:  42 cm\r\n\r\nTủ quần áo 2 cánh:\r\nChiều cao: 190 cm\r\nChiều rộng: 120 cm\r\nChiều sâu:  58 cm', 'Gỗ thông', 'Gemmy wood', 19614184, 17900000, 12500000, 'Bộ tủ quần áo gỗ thông', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '6bcd08e4-eabe-49f2-ba24-6433a30a924c', 'sp-tu-2.png'),
('cba6df98-bb53-4b66-baed-2f3ccdf05f01', 'Ghế ăn gỗ Sồi', 'Rộng: 48 cm\r\nSâu: 50 cm\r\nCao: 83 cm', 'Gỗ sồi', 'Gemmy wood', 19414485, 1170000, 950000, 'Ghế ăn gỗ Sồi', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '728bb108-c820-40f6-9f96-30434a486c02', 'sp-ghe-an-go-soi-1.png'),
('cea45034-afaf-4df4-88ed-1518034b3899', 'Giường ngủ gỗ Thông', 'Chiều cao đầu giường: 102 cm\r\nChiều cao chân giường: 61.5 cm\r\nChiều dài: 200 cm\r\nChiều rộng: 150 cm', 'Gỗ thông', 'Gemmy wood', 255255255, 18500000, 13900000, 'Giường ngủ gỗ Thông', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '7a7b922a-2ccd-441d-8a38-c89746772fb4', 'giuong4.png'),
('d6ff20c3-036b-44da-998e-35970ef9707d', 'Bộ ghế Sofa nỉ hiện đại', '2 Ghế sofa hai chỗ: Chiều cao: 72cm Chiều rộng: 75 cm Chiều dài: 180 cm / Bàn: Chiều cao: 45 cm Chiều dài: 120 cm Chiều rộng: 58 cm', 'Gỗ thông', 'Gemmy wood', 183182180, 38600000, 33900000, 'Bộ ghế Sofa nỉ hiện đại', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', 'fa6423d6-c959-482c-9d24-bb27e91b946d', 'sofa1.png'),
('f2f8ab6e-ad19-49ba-a5e3-9e2ebcf11f78', 'Giường đơn gỗ óc chó', 'Chiều cao đầu giường: 90 cm\r\nChiều cao chân giường: 60 cm\r\nChiều dài: 195 cm\r\nChiều rộng: 140 cm', 'Gỗ óc chó', 'Gemmy wood', 253242134, 26500000, 20900000, 'Giường đơn gỗ óc chó', 'Sản phẩm này được bảo hành 1 năm bao gồm các lỗi sản xuất, các vấn đề về mối mọt. Đối với các sản phẩm được bọc, bảo hành áp dụng cho khung, đệm và các cơ chế, nếu có.', 1, '2021-09-19 00:00:00', '2021-09-19 00:00:00', '7a7b922a-2ccd-441d-8a38-c89746772fb4', 'giuong1.png');

-- 
-- Dumping data for table orderdetail
--
INSERT INTO orderdetail VALUES
('37bcbf03-4060-11ec-a7c5-b00cd19df262', 'aa80041c-a5d3-4e49-8132-477554221978', 3, 'Bộ ghế Sofa gỗ Mun'),
('37bcbf03-4060-11ec-a7c5-b00cd19df262', '04c7f523-39b2-410f-9a34-c23e7ef35bdb', 3, 'Bộ bàn ăn 4 ghế gỗ Sồi'),
('a23b8f20-5bb3-11ec-8664-b00cd19df262', '536e528a-df82-43a2-95e5-9e8c52b49924', 1, 'Bộ ghế Sofa gỗ Óc chó');

-- 
-- Dumping data for table `order`
--
INSERT INTO `order` VALUES
('0530d44e-34d9-11ec-9f32-b00cd19df262', '37bcbf03-4060-11ec-a7c5-b00cd19df262', '2021-11-08 13:50:53', '2021-11-08 13:50:53', '12312', '23123213', '1231231', 1, '12312312', 'dat123456', 4),
('0530d44e-34d9-11ec-9f32-b00cd19df262', 'a23b8f20-5bb3-11ec-8664-b00cd19df262', '2021-12-13 08:26:02', '2021-12-13 08:26:02', 'dat123456', 'hn', '111111111', 1, '1111', 'dat123456', 5);

-- 
-- Dumping data for table news
--
INSERT INTO news VALUES
('bba6d0b9-e91e-4b20-94b7-14ba860d21bd', 'Báo giá sàn gỗ 2020, Giá sàn gỗ công nghiệp Việt Nam, Hàn Quốc', 'Những sản phẩm sàn gỗ công nghiệp đến từ Hàn Quốc luôn đạt được sự tinh tế trong thiết kế và nhẹ nhàng trong màu sắc, sàn gỗ Hàn Quốc là dòng sản phẩm sàn nằm trong top đầu những loại sàn gỗ công nghiệp được nhập khẩu về Việt Nam sớm nhất từ những năm 2000. Sàn gỗ công nghiệp Hàn Quốc luôn được nhiều khách hàng yêu thích không chỉ bởi màu sắc sàn trang nhã, vân gỗ sang trọng mà giá sàn gỗ công nghiệp Hàn Quốc cũng vô cùng phù hợp với khả năng tài chính của người dùng. Bên dưới là giá chi tiết hai dòng sàn gỗ Hàn Quốc DONGWHA và Hansol phổ biến nhất hiện tại.\r\n\r\nSàn gỗ DONGWHA (dày 8mm) : 265.000 đ/m2 bảo hành 10 năm.\r\nSàn gỗ Hansol (dày 8mm) : 270.000 đ/m2 bảo hành 10 năm.\r\n\r\nSàn gỗ công nghiệp Hàn Quốc thuộc dòng sàn gỗ công nghiệp chịu nước phù hợp với thời tiết thay đổi thất thường tại Việt Nam. Sàn gỗ Hàn Quốc với lõi HDF cứng cáp cùng bề mặt chống trầy AC4 cho sàn ổn định theo thời gian sử dụng. Vậy những ưu, khuyết điểm nào làm nên thương hiệu của dòng sàn gỗ công nghiệp Hàn Quốc?', 'newss1.jpg', 1, 1, 0, 1, 1, '2021-09-19 00:00:00', NULL),
('bba6d0b9-e91e-4b20-94b7-14ba860d21be', 'Ý tưởng sử dụng gỗ nhựa ngoài trời Awood trang trí cho hồ bơi & sân vườn cực đẹp', 'Nếu bạn đang ấp ủ ý tưởng về một bể bơi trong sân nhà thì đừng ngần ngại. Mùa hè này chính là thời điểm thích hợp để biến mơ ước này thành hiện thực với vô vàn thiết kế đẹp mắt dành cho bạn.\r\n\r\nNếu bạn đang ấp ủ ý tưởng về một bể bơi trong sân nhà thì đừng ngần ngại. Mùa hè này chính là thời điểm thích hợp để biến mơ ước này thành hiện thực với vô vàn thiết kế đẹp mắt dành cho bạn.\r\n\r\nBơi lội là một trong những cách tốt nhất để giữ dáng và bảo vệ sức khỏe; tuy nhiên việc đi đến các hồ bơi công cộng lại khiến bạn có nhiều e ngại. Bạn muốn có một bể bơi của riêng mình nhưng sân sau lại quá hẹp? Thật ra vấn đề này đã được giải quyết, một bể bơi nho nhỏ dành riêng cho khoảng sân sau nhỏ là một điều hoàn toàn có thể thực hiện được.', 'newss2.jpg', 1, 0, 1, 1, 1, '2021-09-19 00:00:00', NULL),
('bba6d0b9-e91e-4b20-94b7-14ba860d21bf', 'Ý tưởng màu sắc thiết kế đương đại', 'Không gian thiết kế trên được lên ý tưởng bởi Charles và Ray Eames, là sự kết hợp những chiếc ghế đơn mang biểu trưng sự hiện đại, chiếc ghế cong mang cảm giác thoải mái ở màu sắc tươi mới, kết hợp chân ghế biểu tưởng tháp Eiffel, với bàn lớn mặt bàn trang trí đá hoa cương cho không gian tươi mát, mang các thành viên gia đình quây quần bên nhau vui đùa.', 'newss2.jpg', 1, 1, 1, 0, 1, '2021-09-19 00:00:00', NULL);

-- 
-- Dumping data for table contact
--
INSERT INTO contact VALUES
('34003d59-34cd-11ec-9f32-b00cd19df262', '1', '1', '', '', '2021-10-24 20:20:48', '2021-10-24 20:20:48');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;